notebook_project/notebook_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('notes/', include('notes.urls')),
    path('user/', include('users.urls')),
    path('api_v1/', include('api_v1.urls')),
]

notebook_project/notes/urls.py
from django.urls import path
from notes import views

app_name = "note"

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('<int:pk>', views.NoteDetailView.as_view(), name='detail'),
    path('list/', views.NoteListView.as_view(), name='list'),
    path('new/', views.NoteCreateView.as_view(), name='create')
]

notebook_project/users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from users import views

app_name = "users"

urlpatterns = [
    path('register/', views.RegisterCreateView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    
]

notebook_project/notes/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Note(models.Model):
    title = models.CharField(max_length=20, help_text="筆記標題")
    content = models.TextField(max_length=200, help_text="內容")
    created_at = models.DateTimeField(auto_now=True, help_text="建立時間")
    category = models.ForeignKey(Category, 
                                 on_delete=models.CASCADE, 
                                 related_name='notes',
                                 help_text="分類")
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='notes',
                               blank=True, null=True,
                               help_text="作者")

    def __str__(self):
        return self.title

notebook_project/notes/forms.py
from django import forms
from django.contrib.auth.models import User
from notes.models import *

# class NoteForm(forms.Form):
#     title = forms.CharField(max_length=20, required=True)
#     content = forms.CharField(max_length=500, )

class NoteForm(forms.ModelForm):
    def clean_title(self):
        title = self.cleaned_data.get('title')
        if not title:
            raise forms.ValidationError('Title 不可空白!!!')
        note = Note.objects.filter(title=title).first()
        if note:
            raise forms.ValidationError('Title 已存在!!!')
        return title
    def clean_category(self):
        category = self.cleaned_data.get('category')
        if not category:
            raise forms.ValidationError("Category不可空白")
        return category
    def clean_content(self):
        content = self.cleaned_data.get('content')
        if len(content) < 11:
            raise forms.ValidationError('Content 需大於10個字元!!!')
        return content
    def clean(self):
        clean_date = super().clean()
        title = self.cleaned_data.get('title')
        content = self.cleaned_data.get('content')
        if title and content and title in content:
            raise forms.ValidationError('內容不可包含Title!!!')
        return clean_date
    class Meta:
        model = Note
        # fields = '__all__'
        fields = ['title', 'category', 'content']

notebook_project/notes/views.py
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from notes.models import Note
from notes.forms import NoteForm

class NoteListView(LoginRequiredMixin, generic.ListView):
    model = Note
    def get_queryset(self):
        return Note.objects.filter(author=self.request.user)
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "筆記"
        return context

class NoteDetailView(LoginRequiredMixin, generic.DetailView):
    model = Note
    def get_queryset(self):
        return Note.objects.filter(author=self.request.user)
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = self.get_object().title
        return context

class NoteCreateView(LoginRequiredMixin, generic.CreateView):
    model = Note
    # fields = ["title", "content"]
    form_class = NoteForm
    # template_name = "create_note_form.html"
    success_url = reverse_lazy("note:list")
    def form_valid(self, form):
        # form.instance: 未被儲存的新物件 or 編輯中的物件
        form.instance.author = self.request.user
        return super().form_valid(form)
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "新增筆記"
        return context

notebook_project/notes/templates/notes/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <title>NoteBook-{{ title }}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'note:list' %}">NoteBook</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <!-- <a class="nav-link active" href="#">Home <span class="sr-only">(current)</span></a> -->
              <a class="nav-link {% if request.path == '/notes/new/' %}active{% endif %}" href="{% url 'note:create' %}">Create new note</a>
            </div>
        </div>
        <div class="d-flex justify-content-end collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="d-flex justify-content-end navbar-nav ">
              {% if user.is_authenticated %}<span class="navbar-text">{{ user.username }}</span>{% endif %}
              {% if not user.is_authenticated %}
              <a class="nav-link {% if request.path == '/user/register/' %}active{% endif %}" href="{% url 'users:register' %}">Register</a>
              <a class="nav-link {% if request.path == '/user/login/' %}active{% endif %}" href="{% url 'users:login' %}">Login</a>
              {% endif %}
              {% if user.is_authenticated %}
              <form method="post" action="{% url 'users:logout' %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-outline-danger">登出</button>
              </form>
              {% endif %}
            </div>
        </div>
    </nav>
    <div class="container">
        <h1>{{ title }}</h1>
        <hr/>
        {% block container %}
        {% endblock %}
    </div>
    

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    -->

    {% load static %}
    <script src="{% static 'notes/js/main.js' %}"></script>
  </body>
</html>

notebook_project/notes/templates/notes/new.html
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

notebook_project/notes/templates/notes/note_detail.html
{% extends "notes/base.html" %}
{% block container %}
    {% if object %}
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">{{ object.title }}</h5>
                <!-- <h6 class="card-subtitle mb-2 text-muted">{{ object.created_at }}</h6> -->
                <p class="card-text">{{ object.content }}</p>
            </div>
            <div class="card-footer">
                <small class="text-muted">{{ object.created_at }}</small>
            </div>
        </div>
    {% endif %}
{% endblock %}

notebook_project/notes/templates/notes/note_form.html
{% extends "notes/base.html" %}
{% load crispy_forms_tags %}
{% block container %}
    {% if form %}
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Save">
        </form>
    {% endif %}
{% endblock %}

notebook_project/notes/templates/notes/note_list.html
{% extends "notes/base.html" %}
{% block container %}
    {% if note_list %}
        <div class="list-group">
            {% for note in note_list %}
                <a href="{% url 'note:detail' note.pk %}" class="list-group-item list-group-item-action">{{ note.title }}</a>
            {% endfor %}
        </div>
    {% endif %}
    <input type="button" value="更新html" id="btn">
    <div id="msg">原div</div>
{% endblock %}